# Rule for transcript analysis

rule analyze_transcripts:
    input:
        gtf = '{gtf}.gtf',
        bam = '{bam}.bam'
    output:
        '{gtf}_{bam}_{tolleranza}_transcript_analysis.txt'
    params:
        tolleranza = '{tolleranza}',
    shell:
        '''
        python3 main.py {input.gtf} {input.bam} {params.tolleranza} > {output}
       '''

# Rule for Deleting Temporary Files

rule clean:
    shell:
        '''
        rm -f *_transcript_analysis.txt
        '''
